# -*- coding: utf-8 -*-
"""DSP_LAB4Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfX6RHdTqM9SRFQ-KngE5KPF2XVH_xCC

1.Importing the required libraries=>numpy,pandas,matplotlib and seaborn
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""2.Load the dataset into pandas dataframe"""

df=pd.read_csv('/content/Customer Purchasing Behaviors.csv')
df.head()

"""3.Displaying the number of rows and columns in the dataset"""

print("the number of columns are:",df.columns.size)
print("the number of rows are:",df.shape[0])

"""4.Printing the column names of the dataset"""

print("The column names of the dataset are:",np.array(df.columns))
columns=np.array(df.columns)

"""5.Displaying the first 5 rows of the dataset using head function in the pandas"""

df.head()

"""6.Checking the datatype of each column"""

print("The datatypes of each column are:\n",df.dtypes)

"""7.Idetifying the number of missing values in each column"""

print("the number of missing values in each column are:\n",df.isnull().sum())

"""8.Fill missing values in numerical columns using the mean."""

df.fillna(df.mean(numeric_only=True),inplace=True)

"""9.Fill missing values in categorical columns using the mode.

"""

cat_cols=df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].apply(lambda x:x.fillna(x.mode()[0]))

"""10.Verify that there are no missing values remaining."""

df.isnull().sum()

"""11.Calculate the mean for all numerical columns."""

print("the mean of the all the numberical columns are:\n",df.mean(numeric_only=True))

"""12.Calculate the median for all numerical columns"""

print("the median of all the required columns are:\n",df.median(numeric_only=True))

"""13.Calculate the standard deviation for all the numerical columns"""

print("the standard deviation of all the numerical columns:\n",df.std(numeric_only=True))

"""14.Find the minimum and maximum values of all the numerical columns"""

print("the minimum values of all the numberical columns are:\n",df.min(numeric_only=True))
print("the maximum values of all the numerical columns are:\n",df.max(numeric_only=True))

"""15.Generate a summary using describe()"""

df.describe()

"""16.Create a histogram for the purchase amount column."""

plt.hist(df['purchase_amount'])
plt.xlabel('purchase_amount')
plt.ylabel('Frequency')
plt.title('Histogram of purchase_amount')
plt.show()

"""17.Create a bar chart showing the count of customers by product category."""

counts = df['region'].value_counts()
plt.bar(counts.index, counts.values)
plt.xlabel('Region')
plt.ylabel('Number of Customers')
plt.title('Customers by Region')
plt.xticks(rotation=45)
plt.show()

"""18.Create a box plot for the purchase amount column."""

plt.boxplot(df['purchase_amount'],vert=False)
plt.xlabel('purchase amount')
plt.title('Box plot for purchase amount')
plt.grid(True)
plt.show()

"""19.Create a scatter plot between age and purchase amount.(using matplotlib)"""

plt.scatter(df['age'],df['purchase_amount'])
plt.xlabel('age')
plt.ylabel('purchase amount')
plt.title('Scatter plot for the age and purhcase amount')
plt.grid(True)
plt.show()

"""20.Display a correlation heatmap for numerical columns.(using sns)"""

num_df = df[['age', 'annual_income', 'purchase_amount','loyalty_score', 'purchase_frequency']]
corr=num_df.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr,annot=True,cmap='plasma')
plt.title('Correlation Heatmap')
plt.show()